config/routes.rb
Rails.application.routes.draw do
resources :entries
root to: "entries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats, :meal)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div class="message is-danger">
      <div class="message-header">
        <p><%= pluralize(entry.errors.count, "error") %> Couln't saves this entry, review the errors:</p>
      </div>

      <div class="message-body">
        <ul>
          <% entry.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :meal_type, class: "label" %>
    <%= form.text_field :meal_type, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :calories, class: "label" %>
    <%= form.number_field :calories, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :proteins, class: "label" %>
    <%= form.number_field :proteins, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :carbohydrates, class: "label" %>
    <%= form.number_field :carbohydrates, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :fats, class: "label" %>
    <%= form.number_field :fats, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :meal, class: "label" %>
    <%= form.text_field :meal, class: "input" %>
  </div>

  <div class="actions">
    <%= form.submit class: "button is-success" %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="columns is-centered ml-6">
    <div class="column is-one-third">
    <h1 class="is-size-2 has-text-weight-bold mb-3"> Edit your entry</h1>
    <%= render "form", entry: @entry %>
    </div>
</div>

app/views/entries/index.html.erb
<% content_for :title do %>
  Foodlog &ndash; <%= DateTime.now.to_s(:formated_date) %>
<% end %>

<div class="columns mt-6 is-centered">
  <% @entries.each do |entry| %>
    <div class="column is-one-quarter">
      <div class="card">
        <header class="card-header">
          <span class="card-header-title"><%= entry.meal %></p>
        </header>
        <div class="card-content">
          <div class="content">
            <p><span class="has-text-weight-bold"><%= entry.meal_type %></span></p>
            <p><span class="has-text-weight-bold"><%= entry.calories %></span> calories </p>
            <p><span class="has-text-weight-bold"><%= entry.proteins %></span> grams proteins </p>
            <p><span class="has-text-weight-bold"><%= entry.carbohydrates %></span> grams carbohydrates </p>
            <p><span class="has-text-weight-bold"><%= entry.fats %></span> grams fats </p>
            <p class="italic"> Logged <%= time_ago_in_words(entry.created_at) %> ago </p>
          </div>
        </div>
        <footer class="card-footer">
          <%= link_to "Show", entry, class: "card-footer-item" %>
          <%= link_to "Edit", edit_entry_path(entry), class: "card-footer-item" %>
          <%= link_to "Destroy", entry, method: :delete, data: { confirm: "Are you sure?" }, class: "card-footer-item" %>
        </footer>
      </div>
    </div>
  <% end %>
</div>

app/views/entries/new.html.erb
<div class="columns is-centered ml-6">
    <div class="column is-one-third">
    <h1 class="is-size-2 has-text-weight-bold mb-3"> New entry</h1>
    <%= render "form", entry: @entry %>
    </div>
</div>

app/views/entries/show.html.erb
<% content_for :title do %>
    <%= @entry.meal %> &mdash; <%= @entry.created_at.to_s(:formated_date) %>
<% end %>
<div class="columns mt-6 is-centered">
  <div class="column is-one-third">
  <nav class="panel is-link">
    <p class="panel-heading">
      <%= @entry.meal %>
    </p>
    <div class="panel-block">
      Meal Type: <%= @entry.meal_type %>
    </div>
    <div class="panel-block">
      Calories: <%= @entry.calories %>
    </div>
    <div class="panel-block">
      Proteins: <%= @entry.proteins %>
    </div>
    <div class="panel-block">
      Carbohydrates: <%= @entry.carbohydrates %>
    </div>
    <div class="panel-block">
      Fats: <%= @entry.fats %>
    </div>
  </nav>
  <div class="columns is-mobile">
    <div class="column">
      <%= link_to "Edit", edit_entry_path(@entry), class: "button is-success" %>
      <%= link_to "Delete", entry_path(@entry), method: :delete,
                                                data: { confirm: "Are you sure?" },
                                                class: "button is-danger" %>
    </div>
    <div class="column ">
    </div>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <%= render "shared/header" %>
    <div class="container">
      <% if notice.present? %>
        <div class="notification is-link is-light"><%= notice %></div>
      <% end %>

      <% if alert.present? %>
        <div class="notification is-danger is-light"><%= alert %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<section class="hero is-link is-small">
<!-- Hero head: will stick at the top -->
<div class="hero-head">
	<nav class="navbar">
	<div class="container">
		<div class="navbar-brand">
		<%= link_to root_path, class: "navbar-item" do %>
			<h1 class="has-text-weight-bold is-size-4 ml-4">Foodlog</h1>
		<% end %>
		<span class="navbar-burger" data-target="navbarMenuHeroA">
			<span></span>
			<span></span>
			<span></span>
		</span>
		</div>
		<div id="navbarMenuHeroA" class="navbar-menu">
		<div class="navbar-end">
			<span class="navbar-item">
				<%= link_to "Create new entry", new_entry_path, class: "button is-success" %>
			</span>
		</div>
		</div>
	</div>
	</nav>
</div>

<!-- Hero content: will be in the middle -->
<div class="hero-body">
	<div class="container has-text-centered">
	<p class="title">
	<% if content_for(:title) %>
		<%= yield :title %>
	<% else %>
		Foodlog
	<% end %>
	</p>
</div>
</section>